In [1]:
import os
os.getcwd()

'/home/z/220117bd'

In [2]:
os.chdir(".")

In [5]:
f = open("file.txt", "wt")
f

<_io.TextIOWrapper name='file.txt' mode='wt' encoding='UTF-8'>

In [6]:
f.write("String1\n")

8

In [7]:
f.write("String2\n")

8

In [8]:
f.write("String3\n")

8

In [9]:
f.tell()

24

In [10]:
f.write("String4\n")

8

In [11]:
f.tell()

32

In [12]:
f.close()

In [13]:
f = open("file.txt", "at")

In [14]:
f.tell()

32

In [15]:
f.write("String5\n")

8

In [16]:
f.close()

In [17]:
f = open("file.txt", "rt")
f.tell()

0

In [18]:
s = f.read()
s

'String1\nString2\nString3\nString4\nString5\n'

In [19]:
f.read()

''

In [20]:
f.close()

In [21]:
f = open("file.txt", "rt")
f.readline()

'String1\n'

In [22]:
f.readline()

'String2\n'

In [23]:
while line := f.readline():
        print(line)

String3

String4

String5



In [24]:
f.close()

In [25]:
f = open("file.txt", "rt")
for line in f:
    print(line)

String1

String2

String3

String4

String5



In [26]:
f.close()

In [ ]:
f = None
try:
    f = open(...)
    ...
    ...
finally:
    if f is not None:
        f.close()

In [27]:
with open("file.txt", "rt") as f:
    for line in f:
        print(line)

String1

String2

String3

String4

String5



In [28]:
f.closed

True

In [29]:
obj1 = {"qwe": (1, 2, 3), 123: "abc"}

In [30]:
str(obj1)

"{'qwe': (1, 2, 3), 123: 'abc'}"

In [31]:
import pickle

# dump/dumps, load/loads

In [32]:
s = pickle.dumps(obj1)
s

b'\x80\x04\x95\x1b\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\x03qwe\x94K\x01K\x02K\x03\x87\x94K{\x8c\x03abc\x94u.'

In [33]:
obj2 = pickle.loads(s)
obj2

{'qwe': (1, 2, 3), 123: 'abc'}

In [34]:
obj1 == obj2

True

In [35]:
with open("obj.pickle", "wb") as f:
    pickle.dump(obj1, f)

In [36]:
with open("obj.pickle", "rb") as f:
    obj2 = pickle.load(f)
    
obj1 == obj2

True

In [37]:
import json

s = json.dumps(obj1)
s

'{"qwe": [1, 2, 3], "123": "abc"}'

In [38]:
obj1

{'qwe': (1, 2, 3), 123: 'abc'}

In [39]:
obj2 = json.loads(s)
obj2

{'qwe': [1, 2, 3], '123': 'abc'}

In [40]:
data = (
    (123, "abc"),
    (234, 'abc, "def"')
)

In [41]:
import csv

In [42]:
with open("file.csv", "wt") as f:
    w = csv.writer(f)
    for row in data:
        w.writerow(row)

In [44]:
with open("file.csv", "rt") as f:
    r = csv.reader(f)
    for row in r:
        print(row)

['123', 'abc']
['234', 'abc, "def"']


In [45]:
!pip install numpy

     |████████████████████████████████| 16.8 MB 1.4 MB/s eta 0:00:01
You should consider upgrading via the '/home/z/220117bd/env/bin/python3 -m pip install --upgrade pip' command.


In [46]:
import numpy as np

In [47]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [48]:
a.size

4

In [49]:
a.shape

(4,)

In [50]:
a.dtype

dtype('int64')

In [51]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
a.shape

(12,)

In [53]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a[0] = 100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [55]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [57]:
c = a.reshape(2, 3, 2)
c

array([[[100,   1],
        [  2,   3],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]]])

In [60]:
a = np.random.rand(4, 5)
a

array([[0.93963361, 0.08479168, 0.21014837, 0.75409582, 0.17367555],
       [0.51023811, 0.24380469, 0.52509141, 0.9086925 , 0.3747894 ],
       [0.21231325, 0.37315637, 0.34794055, 0.19293146, 0.38384045],
       [0.74916867, 0.81633563, 0.17382246, 0.90179751, 0.50117313]])

In [61]:
b = np.random.rand(4, 5)
b

array([[0.0206159 , 0.84065485, 0.09839966, 0.75009758, 0.92235732],
       [0.30416632, 0.72606772, 0.81165239, 0.18616559, 0.37959444],
       [0.72299595, 0.05547628, 0.45171987, 0.42339602, 0.91796979],
       [0.30623056, 0.18288685, 0.2255649 , 0.72005028, 0.17126436]])

In [62]:
a + b

array([[0.96024951, 0.92544653, 0.30854804, 1.5041934 , 1.09603287],
       [0.81440443, 0.96987241, 1.33674379, 1.09485809, 0.75438384],
       [0.9353092 , 0.42863265, 0.79966042, 0.61632749, 1.30181023],
       [1.05539923, 0.99922248, 0.39938737, 1.6218478 , 0.67243748]])

In [63]:
a*b

array([[0.01937139, 0.07128053, 0.02067853, 0.56564545, 0.16019092],
       [0.15519725, 0.17701871, 0.42619169, 0.16916727, 0.14226797],
       [0.15350162, 0.02070133, 0.15717166, 0.08168641, 0.35235393],
       [0.22941834, 0.14929705, 0.03920825, 0.64933955, 0.08583309]])

In [65]:
a @ b.T

array([[0.83716682, 0.72424979, 1.2576935 , 0.92338525],
       [1.29444122, 1.0698429 , 1.34840183, 1.03777373],
       [0.85106544, 0.79954301, 0.76541496, 0.41640392],
       [1.8575022 , 1.31979644, 1.50733151, 1.15309629]])

In [ ]:
b += a

In [66]:
np.sqrt(b)

array([[0.14358237, 0.91687232, 0.31368721, 0.86608174, 0.96039436],
       [0.55151276, 0.85209607, 0.90091752, 0.4314691 , 0.61611236],
       [0.85029169, 0.23553404, 0.67210109, 0.65068888, 0.9581074 ],
       [0.55338103, 0.42765272, 0.47493674, 0.84855777, 0.41384098]])

In [67]:
a + 5

array([[5.93963361, 5.08479168, 5.21014837, 5.75409582, 5.17367555],
       [5.51023811, 5.24380469, 5.52509141, 5.9086925 , 5.3747894 ],
       [5.21231325, 5.37315637, 5.34794055, 5.19293146, 5.38384045],
       [5.74916867, 5.81633563, 5.17382246, 5.90179751, 5.50117313]])

In [68]:
a + [1, 2, 3, 4, 5]

array([[1.93963361, 2.08479168, 3.21014837, 4.75409582, 5.17367555],
       [1.51023811, 2.24380469, 3.52509141, 4.9086925 , 5.3747894 ],
       [1.21231325, 2.37315637, 3.34794055, 4.19293146, 5.38384045],
       [1.74916867, 2.81633563, 3.17382246, 4.90179751, 5.50117313]])

In [70]:
a + [[1], [2], [3], [4]]

array([[1.93963361, 1.08479168, 1.21014837, 1.75409582, 1.17367555],
       [2.51023811, 2.24380469, 2.52509141, 2.9086925 , 2.3747894 ],
       [3.21231325, 3.37315637, 3.34794055, 3.19293146, 3.38384045],
       [4.74916867, 4.81633563, 4.17382246, 4.90179751, 4.50117313]])

In [71]:
np.mean(a)

0.4688720316313904

In [72]:
np.mean(a, axis=0)

array([0.60283841, 0.37952209, 0.3142507 , 0.68937932, 0.35836963])

In [73]:
np.mean(a, axis=1)

array([0.43246901, 0.51252322, 0.30203642, 0.62845948])

In [74]:
np.nan

nan

In [75]:
a[0][0] = np.nan
a

array([[       nan, 0.08479168, 0.21014837, 0.75409582, 0.17367555],
       [0.51023811, 0.24380469, 0.52509141, 0.9086925 , 0.3747894 ],
       [0.21231325, 0.37315637, 0.34794055, 0.19293146, 0.38384045],
       [0.74916867, 0.81633563, 0.17382246, 0.90179751, 0.50117313]])

In [76]:
np.nan + 3

nan

In [77]:
np.mean(a)

nan

In [78]:
np.nanmean(a)

0.444095106210375

In [79]:
np.nanmean(a, axis=0)

array([0.49057335, 0.37952209, 0.3142507 , 0.68937932, 0.35836963])

In [80]:
a

array([[       nan, 0.08479168, 0.21014837, 0.75409582, 0.17367555],
       [0.51023811, 0.24380469, 0.52509141, 0.9086925 , 0.3747894 ],
       [0.21231325, 0.37315637, 0.34794055, 0.19293146, 0.38384045],
       [0.74916867, 0.81633563, 0.17382246, 0.90179751, 0.50117313]])

In [81]:
a[0][0] = 0.5

In [82]:
a[0]

array([0.5       , 0.08479168, 0.21014837, 0.75409582, 0.17367555])

In [83]:
a[0][0]

0.5

In [84]:
a[0, 0]

0.5

In [85]:
a[:, 1:4]

array([[0.08479168, 0.21014837, 0.75409582],
       [0.24380469, 0.52509141, 0.9086925 ],
       [0.37315637, 0.34794055, 0.19293146],
       [0.81633563, 0.17382246, 0.90179751]])

In [86]:
a[1:3, :]

array([[0.51023811, 0.24380469, 0.52509141, 0.9086925 , 0.3747894 ],
       [0.21231325, 0.37315637, 0.34794055, 0.19293146, 0.38384045]])

In [87]:
a[1:3, 1:4]

array([[0.24380469, 0.52509141, 0.9086925 ],
       [0.37315637, 0.34794055, 0.19293146]])

In [88]:
a[::2, ::2]

array([[0.5       , 0.21014837, 0.17367555],
       [0.21231325, 0.34794055, 0.38384045]])

In [89]:
a

array([[0.5       , 0.08479168, 0.21014837, 0.75409582, 0.17367555],
       [0.51023811, 0.24380469, 0.52509141, 0.9086925 , 0.3747894 ],
       [0.21231325, 0.37315637, 0.34794055, 0.19293146, 0.38384045],
       [0.74916867, 0.81633563, 0.17382246, 0.90179751, 0.50117313]])

In [92]:
a[[(0, 3, 2), (1, 2, 4)]]

/tmp/ipykernel_14018/1347839133.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[[(0, 3, 2), (1, 2, 4)]]


array([0.08479168, 0.17382246, 0.38384045])

In [93]:
a < 0.5

array([[False,  True,  True, False,  True],
       [False,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True, False, False]])

In [94]:
a[a < 0.5]

array([0.08479168, 0.21014837, 0.17367555, 0.24380469, 0.3747894 ,
       0.21231325, 0.37315637, 0.34794055, 0.19293146, 0.38384045,
       0.17382246])

In [95]:
b[a < 0.5]

array([0.84065485, 0.09839966, 0.92235732, 0.72606772, 0.37959444,
       0.72299595, 0.05547628, 0.45171987, 0.42339602, 0.91796979,
       0.2255649 ])

In [96]:
b

array([[0.0206159 , 0.84065485, 0.09839966, 0.75009758, 0.92235732],
       [0.30416632, 0.72606772, 0.81165239, 0.18616559, 0.37959444],
       [0.72299595, 0.05547628, 0.45171987, 0.42339602, 0.91796979],
       [0.30623056, 0.18288685, 0.2255649 , 0.72005028, 0.17126436]])

In [97]:
b[a < 0.5] *= 2

In [98]:
b

array([[0.0206159 , 1.6813097 , 0.19679933, 0.75009758, 1.84471464],
       [0.30416632, 1.45213543, 0.81165239, 0.18616559, 0.75918888],
       [1.4459919 , 0.11095256, 0.90343974, 0.84679204, 1.83593957],
       [0.30623056, 0.18288685, 0.45112981, 0.72005028, 0.17126436]])

In [102]:
x = 1 - 2*np.random.rand(10)
x

array([ 0.3685423 , -0.97726323, -0.87577901, -0.09973446,  0.195435  ,
        0.38029609, -0.22711005,  0.06151486, -0.55059359, -0.60236775])

In [103]:
y = 1 - 2*np.random.rand(10)
y

array([ 0.40063949,  0.49203082, -0.58533934, -0.18004946,  0.12374252,
        0.71749911,  0.04726447,  0.71872991, -0.43270792,  0.79345181])

In [104]:
x*x + y*y < 1

array([ True, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [105]:
np.sum(x*x + y*y < 1)

8

In [109]:
4/(10/8)

3.2

In [123]:
N = 10_000_000
x = 1 - 2*np.random.rand(N)
y = 1 - 2*np.random.rand(N)
4/(N/np.sum(x*x + y*y < 1))

3.1420879999999998

Реализовать возможность сохранения и чтения списка задач в/из файла